language: emacs-lisp
sudo: no

env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - source <(curl --fail --silent --show-error --insecure --location https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw)
  - evm install "$EVM_EMACS" --use --skip

install:
  - cask install

script:
  - cask exec ert-runner
